#include "synth2/oscillator.h"

#include <math.h>

#define PI 3.141592
#define PI2 (2.0 * (PI))

/// Convert midi key into frequency.
static inline double k2f(int16_t k) {
    return 440.0 * exp2((double)(k - 69) / 12.0);
}

/// The wave generation function. Accept following arguments.
/// 1. position in one-cycle wave. Must be in [0, 2π).
/// 2. previously sampled value.
/// 3. duty of the wave, but is maybe unused.
typedef double (*wave_generator)(double, double, double);

/// Sample a point from wava generated by gen function, then increase osc->phase.
static inline double sample(synth2_oscillator_t *osc, wave_generator gen) {
    osc->prev = gen(osc->phase, osc->prev, osc->duty);
    osc->phase += PI2 * k2f(osc->key) / osc->sample_rate;
    if (osc->phase >= PI2) osc->phase -= PI2;
    return osc->prev;
}

static inline double gen_sine(double x, double prev, double duty) {
    return sin(x);
}

static inline double gen_triangle(double x, double prev, double duty) {
    return 0.0;  // TODO
}

static inline double gen_saw(double x, double prev, double duty) {
    return 0.0;  // TODO
}

static inline double gen_square(double x, double prev, double duty) {
    return 0.0;  // TODO
}

static double sample_sine(synth2_oscillator_t *osc) {
    return sample(osc, gen_sine);
}

static double sample_triangle(synth2_oscillator_t *osc) {
    return sample(osc, gen_triangle);
}

static double sample_saw(synth2_oscillator_t *osc) {
    return sample(osc, gen_saw);
}

static double sample_square(synth2_oscillator_t *osc) {
    return sample(osc, gen_square);
}

void synth2_oscillator_init(
    synth2_oscillator_t *osc,
    synth2_oscillator_type_t type,
    double sample_rate,
    int16_t key,
    double duty
) {
    osc->sample_rate = sample_rate;
    osc->key = key;
    osc->phase = 0.0;
    osc->duty = duty;
    osc->prev = 0.0;
    if (type == SYNTH2_OSC_SINE) {
        osc->sample = sample_sine;
    } else if (type == SYNTH2_OSC_TRIANGLE) {
        osc->sample = sample_triangle;
    } else if (type == SYNTH2_OSC_SAW) {
        osc->sample = sample_saw;
    } else {
        osc->sample = sample_square;
    }
}
